config/routes.rb
SyokuninMap::Application.routes.draw do
  get '/', to: 'index#index'
  resources :prefectures, only: :show, shallow: true do
    resources :shokunins
  end

  

end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
  has_many :shokunins
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :shokunin
  after_save do
    shokunin.profile_updated
  end
end

app/models/shokunin.rb
class Shokunin < ActiveRecord::Base
  belongs_to :prefecture
  has_many :profiles, ->{order 'id DESC'}, dependent: :destroy
  belongs_to :profile
  scope :active, ->{where('active = ?',true)}
  def profile_updated
    profile = profiles.first
    self.profile = profile
    self.active = !!profile.try(:active)
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @prefectures = Prefecture.all
    @prefcount={}
    Prefecture.all.each{|pref|
      @prefcount[pref.id]=pref.shokunins.active.count
    }
    max=@prefcount.values.max
    @prefcount.each{|key,value|
      @prefcount[key]=rgb [0xff,0xff,0xff],[0xff,0x00,0x00],value.fdiv(max)
    }
  end
  def rgb(cstart,cend,cval)
    color=3.times.map{|i|cstart[i]+(cend[i]-cstart[i])*cval}.map(&:to_i)
    "#%02x%02x%02x"%color
  end
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  def show
    @prefecture = Prefecture.find params[:id]
    @shokunins = @prefecture.shokunins.order 'updated_at DESC'
  end
end

app/controllers/shokunins_controller.rb
class ShokuninsController < ApplicationController

  before_filter do
    if params[:id]
      @shokunin = Shokunin.find params[:id]
      @prefecture = @shokunin.prefecture
      @profile = @shokunin.profile
    else
      @prefecture = Prefecture.find params[:prefecture_id]
      @shokunin = Shokunin.new
      @profile = Profile.new active: true
    end
  end

  def new
  end

  def edit
  end

  def create
    @shokunin = @prefecture.shokunins.create
    @shokunin.profiles.create shokunin_params
    flash[:success] = "新しいハガキ職人が登録されました"
    redirect_to action: :edit, id: @shokunin.id
  end

  def update
    @shokunin.profiles.create shokunin_params
    flash[:notice] = "ハガキ職人の情報を更新しました"
    redirect_to action: :edit
  end


  private
  def shokunin_params
    params.require(:shokunin).permit(:name, :contact, :content, :active)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :warning then "alert alert-warning"
      when :danger then "alert alert-danger"
    end
  end
end

app/views/index/index.html.erb
<div class="col-md-4" id='shokunins'>
  <span>右の日本地図をクリックするとそこの職人が見えます</span>
  <% @prefectures.each do |pref| %>
    <div id='pref<%= pref.id %>'>
      <h3><%= pref.name %>にいるハガキ職人一覧</h3>
      <div style="width: 100%;">
        <div style="float:right; margin-bottom: 10px;">
          <i class="glyphicon glyphicon-edit"></i><%= link_to 'ハガキ職人の追加・編集', prefecture_path(pref) %>
        </div>
      </div>
      <ul style="clear:right;padding: 0;list-style: none;">
        <% pref.shokunins.active.each do |shokunin| %>
          <li style="background: #F4F4F4;margin-bottom: 5px;">
            <div class="shokunin" style='font-size:23px;padding:5px;'>
              <%= shokunin.profile.name %><span style="float:right;font-size:12px;padding-top: 15px;">クリックすると詳細が開きます</span>
            </div>
            <div class="shokunin-info" style="padding-left: 8px;display:none;">
              <div>Twitterアカウント：<%= shokunin.profile.contact %></div>
              <div>主な投稿番組：<%= shokunin.profile.content %></div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

<div class="col-md-8">
  <div id='foobar' class='japan-svg-map' data-width='600' data-height='660' data-src='<%= image_path 'japan.svg' %>' data-pref-color='<%= @prefcount.to_json %>' style='background:#eef'>
    <div style='line-height:440px;text-align:center'>loading...</div>
  </div>
</div>

app/views/layouts/_header.html.erb
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">ハガキ職人マップ</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">ホーム</a></li>
          <li><a href="#about">このサイトについて</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SyokuninMap</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container" style="padding-top:60px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/prefectures/show.html.erb
<h1><%= @prefecture.name %></h1>
<%= link_to '新規作成', new_prefecture_shokunin_path(@prefecture) %>
<ul>
<% @shokunins.each do |shokunin| %>
  <li>
    <div class=name>
      <%= link_to edit_shokunin_path(shokunin) do %>
        <%= '(削除)' unless shokunin.active? %>
        <%= shokunin.profile.name %>
      <% end %>
    </div>
    <div class=contact><%= shokunin.profile.contact %></div>
    <div class=content><%= shokunin.profile.content %></div>
  </li>
<% end %>
</ul>

app/views/shokunins/_form.html.erb
<div class="col-md-6">
  <h2><%= @prefecture.name %>にいるハガキ職人を<%=title%>する</h2>
  <%= form_for url do |f| %>
    ラジオネーム
    <%= text_field_tag 'shokunin[name]', @profile.name, class: "form-control" %>
    <br>
    TwitterアカウントやブログのURLなど
    <%= text_field_tag 'shokunin[contact]', @profile.contact , class: "form-control"%>
    <br>
    主に投稿している番組
    <%= text_area_tag 'shokunin[content]', @profile.content, class: "form-control" %>
    <br>
    active
    <%= check_box_tag 'shokunin[active]', true, ({checked: true} if @profile.active?) %>
    <br>
    <%= submit_tag '完了する', class: "btn btn-default"  %>
  <% end %>
</div>

<% if title == "編集" %>
  <div class="col-md-6">
    <h2>編集履歴<small>クリックするとその編集の内容が反映されます</small></h2>
    <ul>
      <% @shokunin.profiles.each do |profile| %>
        <%= content_tag :li, data: profile.as_json, class: :past_profiles do %>
          <div><%= '(削除)' unless profile.active? %>-<%= profile.name %></div>
          <div><%= profile.contact %></div>
          <div><%= profile.content %></div>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shokunins/edit.html.erb
<%= render partial: 'form', locals: {url: @shokunin, title: "編集"} %>

app/views/shokunins/new.html.erb
<%= render partial: 'form', locals: {url: [@prefecture, @shokunin], title: "登録"} %>